### ISSUE TITLE
LearnFrame and ReviewFrame mockups

### ISSUE THREAD

**Issue by xingl213** [CSC207-UofT/course-project-realmatrix#23]
![LearnFrame mockup](https://user-images.githubusercontent.com/88172544/143494051-4372916d-a084-41dd-a86e-866900b97608.png)
![ReviewFrame mockup](https://user-images.githubusercontent.com/88172544/143494070-23b5330d-e7a3-48cc-bb35-f7ededbea005.png)
@Runshi-Yang 
@ChloeH88 @Ethan-ZYF @ziqishu @JC605 Feel free to modify my mockups.

**Comment by ChloeH88** [comment]
Good work! 

Suggestion: **use `JTextArea` instead of text field**. Text field doesn't support multi-line texts, so term and definition would end up in the same line or too long term won't soft wrap.

For ReviewFrame, not sure if it's reasonable to have "show definition" and "can't recall" buttons on the same page. Even if users can't recall, they can just click show definition and next card... But if to minimize work and save time, that's okay.

**Comment by xingl213** [comment]
@ChloeH88 Good point. Also don't take the words in the parenthesis too literally. Use button prompt that makes sense @Runshi-Yang. For example, name button 1 "show definition", button 2 "remember wrong", button 3 "remember correctly". Something like this.
